### ISSUE TITLE
Dependency on Included Implementation of ES6 Promise polyfill?

### ISSUE THREAD

**Issue by michaelhfreeman** [liferay/liferay-amd-loader#103]
To what degree (if any) is the loader dependent on the included ES6 Promise polyfill?

Put another way, is there anything special about that included implementation that the loader needs to function? -- or does it just care about basic resolve/reject functionality in a typical Promise implementation?

In short I am seeing some funky behavior (that I will admit I don't fully grok just yet) where if i replace the global implementation of Promise after the loader is injected (by including ZoneJS) I start to see some funky behavior in the loader. At this point I can't even make a more educated assessment that to say if I don't replace the loader's Promise implementation, everything works fine, but if I do replace it I start seeing a bunch of "Mismatched anonymous define() module:" warnings that I was not seeing before...

**Comment by yuchi** [comment]
The Loader expects a **good** implementation of the Promises spec to be there. If I recall correctly it polyfills it if necessary.

What implementation are you trying to use?

**Comment by michaelhfreeman** [comment]
In the problematic case I am using a Promise implementation provided by ZoneJs (ZoneAwarePromise), i.e. the Angular 2 use case.....

If i include ZoneJS  first with its implementation of Promise, and then the LR loader follows and overwrites that one, then ZoneJS is mad and complains about someone overwriting his special implementation of Promise. (ZoneAwarePromise)

Then if I let the LR loader go first, and then let ZoneJS goes second with his implementation of Promise, things seem to work, but I get the complaints from the LR loader about ""Mismatched anonymous define() module"

**Comment by yuchi** [comment]
Probably one of the two libraries are depending on some edge case behavior of the promise spec.

Since AMD Loader is pretty agnostic (works with native promises) I infer the issue is in the Zone JS implementation.

**Comment by michaelhfreeman** [comment]
You're probably right--I guess what i need to do next is to see if I can get a better sense of what the "Mismatched anonymous define() module" error is really telling me---

My sense is that it means a standalone script tag came in with a define() for non-existent or unknown dependencies?

**Comment by yuchi** [comment]
More or less that means that `define` has been called without defining a name but the Loader didnt expect an anonymous module.

Well now that I think of it probably the issue is not related to Promises at all.
Let me get to my Mac to answer more thoroughly.

**Comment by michaelhfreeman** [comment]
k--yeah my pure guesswork here is that somehow the swap out of the promises library is affecting the fulfillment/resolution of the dependencies that this module has---

so in the base case C depends on [A,B] and when C calls define([A,B],func) it works...

but then something happens when the Promise impl changes, and now C calls define([A,B],func) and I get this error...

**Comment by yuchi** [comment]
So you actually have an anonymous module (`Liferay.Loader.addModule({ anonymous: true })`, and when you load it without swapping the Promise impl it works.

Did I get the preconditions right?

Did I

**Comment by michaelhfreeman** [comment]
I am still not sure what I managed to screw up but I did manage to fix the issue. Can close this one as an error on my end that from what I can tell had to do with the precisely required sequencing of the ES6 shim, Liferay Loader, and Zone JS. Once i got everything in order its all good now...thanks for your help

**Comment by yuchi** [comment]
Awesome 👏
Glad to help even if I didn't do that much.

**Comment by ipeychev** [comment]
I'm waking up and seeing @yuchi helped here already. Thanks!

About the issue and just FYI, the Loader requires a standard implementation of ES6 promises. It doesn't require anything special (like Cancellable Promises for example). In fact, in Liferay Portal the version with Promises is used, since IE should be supported, but if you don't care about IE (in 2017 it is pretty much normal), you may replace the version with the [pure](https://github.com/liferay/liferay-amd-loader/blob/3be84f96fe5146fd534a20886ae6ce61fb7c60b2/dist/loader-pure-min.js) minimized version and it should work like a charm.

Angular uses ZoneJS and AFAIR ZoneJS is monkey patching everything asynchronous in the browser, so if you use it, you may use use the pure version even on IE.

> If i include ZoneJS first with its implementation of Promise, and then the LR loader follows and overwrites that one, then ZoneJS is mad and complains about someone overwriting his special implementation of Promise. (ZoneAwarePromise)

Hm, that is odd. On which browser was that? IE? Because on the others the shim should not do anything - it should check that the native Promise is available and skip overwriting if so.

Also, as you figured out, ZoneJS should be at the end of the chain to overwrite what they need.

Thanks,

**Comment by mfreeman-xtivia** [comment]
Yeah it looks like at least as implemented in Liferay the loader.js is pretty unequivocal about setting its own version of Promise. I am running Chrome in Windows, and at around line 860 in loader.js I see code like this...

 ```
 @class Promise
  @param {function} resolver
  Useful for tooling.
  @constructor
*/
function Promise(resolver) {
  this[PROMISE_ID] = nextId();
  this._result = this._state = undefined;
  this._subscribers = [];

  if (noop !== resolver) {
    typeof resolver !== 'function' && needsResolver();
    this instanceof Promise ? initializePromise(this, resolver) : needsNew();
  }
}

Promise.all = all;
Promise.race = race;
Promise.resolve = resolve;
Promise.reject = reject;
Promise._setScheduler = setScheduler;
Promise._setAsap = setAsap;
Promise._asap = asap;

Promise.prototype = {
....
```

Its too bad...it would actually be nice if it did check and see if there was already a version of Promise installed but it doesn't look to me like it does any such checking. So its aggravating in that now I have to write and deploy some custom logic to get Zone.js inserted *after* the loader vs just being able to add a couple of global scripts to the header...oh well

**Comment by ipeychev** [comment]
Hey @mfreeman-xtivia,

About 

> it would actually be nice if it did check and see if there was already a version of Promise installed but it doesn't look to me like it does any such checking. 

Since the last time we spoke, there was [this](https://github.com/liferay/liferay-amd-loader/issues/105) issue opened and fixed. Now Promise polyfil exposes a Promise variable in window if there wasn't existing one. This used to be developer's task. Btw, I don't think it is a job of the Loader at all, but this is another story.

To say it clear and shorter:
1. Before v1.5.9, Loader never exposed a Promise to window. There was `window.ES6Promise` in window instead and it was up to the developer to assign it to `window.Promise`.
2. In v1.5.9, if `window.Promise` is not available, such variable will be [created](https://github.com/liferay/liferay-amd-loader/blob/3e6de98a46730fc42c7cc54bac074bf65060af56/src/template/loader.template#L6-L7) with the value of `window.ES6Promise`.

Now, keeping that in mind and looking at your [first](https://github.com/liferay/liferay-amd-loader/issues/103#issue-212202377) original post, maybe we were barking at the wrong tree? Since you were used a version *before* 1.5.9, the global `window.Promise` was never created by the loader, even in IE, where it is not available. After v1.5.9, it is being added *only* if not existing, i.e. Loader never overwrites any value of `window.Promise` - polifilled or not.

You say you run Chrome on Window, in this case you may forget that Loader provides a Promise. It will never overwrite the `window.Promise`, as it should be.

If the Promise, which Zone provides behaves as the native one, everything should work fine and again - Loader doesn't use or provide in the polyfil any non-standard Promise functions.

Hope that helps,

**Comment by mfreeman-xtivia** [comment]
I guess that i still don't understand the assertion that the Loader never overwrites window.Promise?

That code I posted in the previous post is straight from the loader.js being used in Liferay DXP, and there is **zero** conditional logic around the function declaration for Promise() in the global namespace.

**Comment by ipeychev** [comment]
The code you are mentioning is wrapped in a function expression on line [13](https://github.com/liferay/liferay-amd-loader/blob/3e6de98a46730fc42c7cc54bac074bf65060af56/dist/loader.js#L13), which means that the function declaration [```function Promise(resolver) {```](https://github.com/liferay/liferay-amd-loader/blob/3e6de98a46730fc42c7cc54bac074bf65060af56/dist/loader.js#L868) won't leak. On line [12](https://github.com/liferay/liferay-amd-loader/blob/3e6de98a46730fc42c7cc54bac074bf65060af56/dist/loader.js#L12) it is exposed as `global.ES6Promise`, where `global` is `this` - aka window. This matches what I wrote [here](https://github.com/liferay/liferay-amd-loader/issues/103#issuecomment-287519690).

You may try this - please get the code of Loader without the Promise polyfill from [here](https://github.com/liferay/liferay-amd-loader/blob/3e6de98a46730fc42c7cc54bac074bf65060af56/dist/loader-pure.js), put it in Liferay DXP and try with it (or just discard the polyfil from the Loader in DXP). You are using Chrome, so it will work and you may be sure no one from our side will overwrite the native Promise.

**Comment by mfreeman-xtivia** [comment]
Iliyan

I'm not sure how just yet, but i am pretty sure that the loader is wiping out Promise with its own copy.

If you look at the screenshot below you will see a snapshot from Chrome DevTools taken when Zone.js complains about Promise being overwritten. So in this scenario zone.js loads first, then the Liferay loader, and then later the Angular code loading triggers Zone.js to run and it complains about its version of Promise being overwritten.

You can see pretty clearly in the watch window on the right that the function pointer for the Promise prototype points back to the Liferay loader....

![image](https://cloud.githubusercontent.com/assets/10734467/24072597/7c40b2d0-0bb7-11e7-8a8f-e08f8b57463d.png)

**Comment by ipeychev** [comment]
Lets suppose this is true, then my best guess is that:
1. Some code outside the Loader is assigning the polyfil which comes with the Loader to `window.Promise` (maybe some code in Liferay DXP for example, no idea).
2. There is some other library you have installed which comes with a polyfil too and it overwrites the native one.

Which of above is easy to check - remove the promise polifyl from Loader or install the version without the Promise as I described [here](https://github.com/liferay/liferay-amd-loader/issues/103#issuecomment-287545873) and you will know it.

**Comment by mfreeman-xtivia** [comment]
Since I have to ultimately run inside Liferay DXP in production, editing or installing an alternative version of the Loader isn't really an option for me...

And by stepping through the loader code in the debugger, I found that it is in fact loader.js that is overwriting the Zone.js loader. It happens at line #1146 in the code attached a couple of posts back, when the loader makes a unconditional call to polyfill()

**Comment by mfreeman-xtivia** [comment]
And chasing it further, it appears that line 1138 in the polyfill() function is the problem....

` if (promiseToString === '[object Promise]' && !P.cast)` 

fails in this case because promiseToString returns "[object Object]"

**Comment by ipeychev** [comment]
Okay. First of all, we are talking about different versions. I'm talking about the latest version of Loader which includes [ES6Promise **v4.0.5**](https://github.com/liferay/liferay-amd-loader/blob/3e6de98a46730fc42c7cc54bac074bf65060af56/dist/loader.js#L6). However, in the code you [attached](https://github.com/liferay/liferay-amd-loader/issues/103#issuecomment-287539475) I see version **3.3.1**. Maybe this version was broken so we are both correct in what we say :)

Let me do something:
@jbalsas Could you please check and tell me what version of Loader is included in DXP? It looks like @mfreeman-xtivia reports it is some old one (I also assume he has all the latest service packs, etc.).

**Comment by mfreeman-xtivia** [comment]
But it won't matter...

....because even the latest version of the loader (master branch on GitHub) still has this code at line 1142

`if (promiseToString === '[object Promise]' && !P.cast) {`
        
which is always going to fail if promiseToString returns '[object Object]' as it does in this case....

**Comment by ipeychev** [comment]
As I said, the latest version exposes ES6Promise and not Promise. Also, look at this [issue](https://github.com/liferay/liferay-amd-loader/issues/108) from a few days ago. **We explicitly had to assign ES6Promise to Promise** [here](https://github.com/liferay/liferay-amd-loader/blob/3e6de98a46730fc42c7cc54bac074bf65060af56/src/template/loader.template#L5-L9).

**Comment by mfreeman-xtivia** [comment]
I think we are still talking past one another here...my issue is not **what** you polyfill window.Promise with (ie Promise or ES6Promise) but **when** you decide to polyfill it....

I am asserting that your trigger for that decision of whether or not to polyfill is based on the function 'promiseToString' returning '[object Promise']. When that is **not** the case, and that function for example returns '[object Object'] then the polyfill is triggered and the ZoneJs prior implementation of promise is wiped out

**Comment by ipeychev** [comment]
No, we don't. In the latest version of the Polyfil **no one is invoking `polyfill()`** as it was in 3.3.1! It is *only* being [assigned](https://github.com/liferay/liferay-amd-loader/blob/master/dist/loader.js#L1151) to Promise (which is NOT the native one).

Please look at the following screencast which proves the latest version of Loader doesn't overwrite anything:
![loader](https://cloud.githubusercontent.com/assets/78014/24073224/7723b33c-0bf4-11e7-8b9a-ac374b90afea.gif)

**Comment by mfreeman-xtivia** [comment]
Cool thanks that helps---and so in what version of the loader did the change to stop polyfilling window.Promise go in?

**Comment by mfreeman-xtivia** [comment]
Also @jbalsas FWIW and while we are discussing this subject, could you guys please at some point take a look at how you including the es6-promise script file in Liferay? It appears that the version that is shipping was generated with source maps on but the sourcemap is not shipping with Liferay, so when you are debugging in Chrome DevTools you see a billion of these ...

`{code="404", msg="ProxyServlet: /o/frontend-js-web/loader/es6-promise.map", uri=/o/frontend-js-web/loader/es6-promise.map}`

**Comment by ipeychev** [comment]
@mfreeman-xtivia  No idea in which version ES6Promise stopped overwriting the global Promise. We are developing the Loader and we don't care much about the polyfill (at least I don't). We simply drop the latest version of ES6 polyfill there (which is supposed to be battle tested) to fill the gaps in IE.

Btw, and this is FYI only, I thought I have seen everything in this business, but even in my worst nightmares I haven't imagined that there will be some library, which would proudly overwrite the native Promise with its own version and not only that, but it would protest if someone else was doing it too. A developer should be very brave to use it or to have smoked something very strong to use such thing, I personally wouldn't touch it even with a pole for pole vault :D

**Comment by mfreeman-xtivia** [comment]
I can't argue the point about ZoneJS (Angular 2) choosing to nuke the global Promise with its own private copy...

Unfortunately in the real world, with real clients, I don't always get to say "dont use that", particularly when its a framework that has the adoption rate of Angular 2, regardless of what you or I think about some of their coding practices.

**Comment by ipeychev** [comment]
Yeah, I know what you mean. God help them!

**Comment by jbalsas** [comment]
Hey @mfreeman-xtivia, the sourcemap issue was addressed [here](https://github.com/liferay/liferay-amd-loader/issues/88) and released with `1.5.7`. Since then, we have updated Liferay Portal in several occasions, so it should be fixed either in more up-to-date fixpacks or in an upcoming one.

I can try to figure out exactly in which FP we updated the loader past `1.5.6` that is the version with this issue if you need me to.

**Comment by mfreeman-xtivia** [comment]
@jbalsas I have patch level DE12 for DXP installed and I am still getting it by the hundreds unfortunately...

**Comment by jbalsas** [comment]
Hey @mfreeman-xtivia, you are totally right. We skipped `1.5.7` so it never made it into a fixpack. `1.5.9` is already scheduled for FP13, so it should be included as soon as the new fixpack is released.

**Comment by jbalsas** [comment]
Hey @mfreeman-xtivia, I've just realized that the bundle build is not adding the promise map, so it should still be 404'ing as you said. Will open an issue for this tomorrow as soon as I get to the office.

Sorry for the misunderstanding!

**Comment by budkin76** [comment]
I noticed this issue is closed but I'm still getting 404's for `/o/frontend-js-web/es6-promise.map` in the latest version of Liferay DXP with the most recent patch.

**Comment by yuchi** [comment]
While annoying that’s not a real issue since it’s just Source Maps that are not loaded.

Are you just (rightfully) annoyed or are you seeing any issue?

**Comment by mfreeman-xtivia** [comment]
I would argue (again) that this is a **REAL** issue. When extraneous error messages like this are spewing into your console debug log, it has a **major** impact on your ability to do debug work. Especially since this was identified back in March of this year (see the trail on this issue) could we at least get a Liferay ticket opened on it as promised so that we might have some hope that it would actually get fixed one day? Thanks

**Comment by jbalsas** [comment]
Hey @budkin76, @mfreeman-xtivia, this was fixed in [this commit](https://github.com/liferay/liferay-portal/commit/f322e39dccf45e8937e566cf906d3fffe2934862) as part of [LPS-71634](https://issues.liferay.com/browse/LPS-71634) which was backported into GA4 and FP14 back in April. 

Could you please verify if your environment includes those fixes?

**Comment by yuchi** [comment]
@mfreeman-xtivia Yeah, my wording wasn’t the best possible.

**Comment by AhHa45** [comment]
I am on 7.0.10 GA1 (Wilberforce / Build 7010 / June 15, 2016) Patch: de-75-7010  and I am getting also:
```
2019-06-12 21:29:37.931 WARN  [http-nio-8080-exec-6][code_jsp:172] {code="404", msg="ProxyServlet: /o/frontend-js-web/es6-promise.map", uri=/o/frontend-js-web/es6-promise.map}
```
is there a way to fix this issue without upgrading LR version?
It would not bother me but the timeout until the 404 comes annoys me very much as my page is not loaded until that...

**Comment by yuchi** [comment]
@ahha45 cannot help on a solution, but should timeout only when the DevTools are opened, and should bother only the DevTools UI. Nothing in the page actually loads the source map, so it cannot be slowing your page loading. (Unless you are hitting the concurrent request count limit of the browser, therefore slowing *other* resources when DevTools are open)

**Comment by izaera** [comment]
@AhHa45 The problem has been fixed in the loader itself and then the Portal has been pointed to the new version to avoid that failure but of course you need to apply the patches.

If you want to fix it without upgrading Liferay the only possible way I can think of is by patching this module -> https://github.com/liferay/liferay-portal/tree/7.0.x/modules/apps/foundation/frontend-js/frontend-js-web yourself.

Or maybe try to contact Liferay's support if you have a subscription...
