### ISSUE TITLE
How to get Loader version from a running Liferay 7 Portal

### ISSUE THREAD

**Issue by caneta** [liferay/liferay-amd-loader#109]
A simple question: is there a way to get the version of the Liferay AMD Loader currently running on a Liferay 7 Portal?
Something like `Loader.version()` from a browser console?
If, not which files have I to inspect to get this information?
Thank you

**Comment by jbalsas** [comment]
Hey @caneta, I think the closest you can get that information is in the [package.json](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-js/frontend-js-web/package.json#L13) file of the `frontend-js-web` module. As you see, master (and future fix-packs) is in `1.5.9`.

I'm keeping this open because I think we could implement this :)

**Comment by caneta** [comment]
Are you talking about Liferay sources?
Because I have the portal bundled with Tomcat only, right now...is there a way to get Loader version with just that?

**Comment by jbalsas** [comment]
mmm... yeah, in GA3 we were still relying on webjars to distribute the loader. `1.5.2` sounds about right.

We're going to implement this asap, sorry for the inconvenience!

**Comment by caneta** [comment]
No problem @jbalsas, waiting for that feature...thank you!

**Comment by jbalsas** [comment]
Reopening, if just to track it down and make sure we don't forget 😉

**Comment by jbalsas** [comment]
Also, scheduled for milestone `1.6.0`

**Comment by ipeychev** [comment]
This was a good idea and I added this feature [here](https://github.com/liferay/liferay-amd-loader/commit/25b57540114bf4bc981465e4c964a48ad08aa681).

Thanks,
