### ISSUE TITLE
AMD default dependencies are given in wrong order

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-amd-loader#113]
Even though the AMD spec says that when `define()` gets no `dependencies` argument it should assume `["require", "exports", "module"]` was given (https://github.com/amdjs/amdjs-api/blob/master/AMD.md#dependencies- ), we are now assuming `['module', 'exports']`.

Fixing this might break existing code but, on the other hand, if such code exists it is working by coincidence because we are not respecting the spec, so I'm not sure how we should proceed...

Opinions @jbalsas @ipeychev ?

**Comment by jbalsas** [comment]
I think this should be safe to implement... we actually don't know about direct users of our loader that could be greatly impacted and most of our usage is auto-generated, so it would be easy to fix if needed.

If we wanted to be safe, we could set try some kind of a deprecation path, via a `compat mode` or similar, but I don't think it would be necessary...

**Comment by ipeychev** [comment]
Hey Ivan,

First of all, please bear in mind we never had the ambition to create a fully compilant AMD loader. To create another one in 2015... didn't make much sense for us. Our ambition was only to allow people in Liferay to load modules using `import` statements and *only* until browsers started to implement these modules natively. It was expected to happen in 2016, but it didn't. Only Safari has implemented this so far and AFAIK only in some technical preview. We also thought initially to not expose the Loader at all, exactly to not give wrong expectations to the customers, but we couldn't do it (because of the JSPs).

Keeping that in mind, we tried to cover what the transpiers (and especially Babel) were producing this time from `import` statements. It wasn't producing modules with dependencies like `["require", "exports", "module"]`, that's why we haven't implemented it. If it were, we would have implemented `require` too.
The AMD "specification" is full with insane crap, which is not used by 99.9999999% of the modules on Earth and not only that, but also 99.999999% of the developers are not aware of the local require and most of the other "features" of AMD modules. So why implementing this? No one would say us "bravo", because people  are simply not using these features and inside Liferay the transpiler does not use them neither.
You may go ahead and implement this, you won't break existing code.
About implementation, some time ago I went and evaluated what should be done. [Here](https://github.com/liferay/liferay-amd-loader/issues/92#issuecomment-263141438) it is. The implementation won't be that hard.

Thanks,

**Comment by izaera** [comment]
Hi @ipeychev 

I agree that creating another loader is not the goal, and also that we don't need the local require, but I also thing that conforming as much as possible to the spec is a good thing. Implementing the local require looked almost trivial (see https://github.com/liferay/liferay-amd-loader/pull/114) and that's why I added it (except for the "Simplified CommonJS Wrapper" scenario, which I ommited).

What we were initially trying to accomplish was making development workflow with npm much easier. For that, I saw that having a local require could make easier to cut and paste npm modules into Liferay bundles directly, but then I realized that Babel would rewrite the local requires so we wouldn't need it. Nevertheless, as it was done I thought it would be a good idea to be nearer to 100% implementation of the spec.

This issue is along the same lines, that's why I proposed it. I guess I will send a pull to change the default dependencies order, then (given that it doesn't look problematic). That way we will be nearly 100% AMD spec conforming.

Thanks for the feedback :-),
Ivan
