### ISSUE TITLE
Support dependency versions in module definitions

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-amd-loader#116]
This is needed to be able to resolve module dependencies at runtime. 

Imagine a module defined as:

```javascript
define('module', ['require', 'dependency'], function() {
    ...
    var d = require('dependency');
    ...
})
```

where we want to resolve `dependency` to an NPM package but the version can change during runtime (as a consequence of portal server's (un)deployments of OSGi bundles containing NPM modules).

The only way to achieve this behavior is by letting the module define itself without specifying `dependency`'s version in its source code, and letting the loader decide which version to load at runtime.

So, we propose to add an optional `dependencyVersions` field to module configuration and if it is found by the loader, it will change `dependency` to `dependency@version` on the fly.

An example of such configuration follows:

```javascript
    'extender-experiment-portlet@1.0.0/lib/index.es': {
        'path': '/packages/extender-experiment-portlet@1.0.0/lib/index.es.js',
        'dependencies': ['exports', 'isarray', 'isobject'],
        'dependencyVersions': {
            'isarray': '2.0.1',
            'isobject': '2.1.0'
        }
    }
```

**Comment by jbalsas** [comment]
Hey @izaera, sorry to jump into this so late, but I was looking into `systemjs`, and this is more or less [`map`](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages) to them.

Would it make sense for us to follow something like that? We could have:

```javascript
    'extender-experiment-portlet@1.0.0/lib/index.es': {
        'path': '/packages/extender-experiment-portlet@1.0.0/lib/index.es.js',
        'dependencies': ['exports', 'isarray', 'isobject'],
        'dependencyVersions': {
            'isarray': 'isarray@2.0.1',
            'isobject': 'isobject@2.1.0'
        }
    }
```

Wouldn't this be even easier to implement?

**Comment by jbalsas** [comment]
They also have [contextual map configuration](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#map) which would be the equivalent for us to something like:

```javascript
__CONFIG__.maps = {
    'extender-experiment-portlet': {
        'isarray': 'isarray@2.0.1',
        'isobject': 'isobject@2.1.0'
    }
};
```

**Comment by ipeychev** [comment]
Yeah, from Loader's point of view, this is even better - it is more general approach and more consistent - one mapping does everything. It won't be hard to implement.

However, let's keep in mind we don't make a clone of RequireJS or SystemJS - we make something specific for Portal and we have specific requirements. Most of the configuration of the Loader (if not the all of it), will be generated automatically, so if "dependencyVersions" is more clear for Liferay's developers and it will do the job - let's go with it.
Another option (I guess it has been discussed already, so please let me know if it makes sense), is to split those - in Loader it could be with mapping for simplicity and consistency, but Liferay developers may write in their configs "dependencyVersions".
Why? I still somehow try to hide Loader from developer's eyes and haven't lost my hope that we can drop it, as we planned. That's why the accent for me is not on the Loader, but on what developers write in their config files. We have to keep the Loader invisible, ready to disappear any time.

If it doesn't matter and no one cares if it is "dependencyVersions" or "map" in module's configuration, then let's go with map.

Thanks,

**Comment by izaera** [comment]
I have changed `dependencyVersions` to `map` as suggested by @jbalsas :+1:
