### ISSUE TITLE
Don't resolve dependencies each time require() is called

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-amd-loader#159]
Currently, the dependencies of a module are always resolved when require is called. This puts an overhead of around 8 ms in my computer with an standard portal.

What we want is to resolve only once. This is a breaking change as configuration is NOT read only, but we'll assume for the next version that it is and provide an API to mark modules as not cacheable. This decision is made because we think that changing the config during runtime is a corner case that probably nobody is using.

**Comment by yuchi** [comment]
> This decision is made because we think that changing the config during runtime is a corner case that probably nobody is using.

IMHO, a corner case that probably nobody *should be* using.

***But:*** what if the user is navigating in the portal, and during that time a deploy happened? Since we have Senna everywhere we would be in a bad situation where the configuration cannot be updated.

Probably, using a timestamp on the config (built from the portal) we can **know** that the configuration must be updated and resolution caches be invalidated.

What do you think?

**Comment by izaera** [comment]
@yuchi see https://github.com/liferay/liferay-amd-loader/issues/160 👍
