### ISSUE TITLE
addModule removed?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/liferay-amd-loader#210]
Receiving errors that Liferay.Loader.addModules is not a function in DXP 7.2

Was this function removed from the loader in 7.2? And if so does that mean we can no longer do programmatic loading of modules?

**Comment by izaera** [comment]
> Was this function removed from the loader in 7.2? 

Yes. Since we merged #185 and released loader 4.0, the Portal started to use it. Because #185 implies doing all module resolutions in the server side to hugely boost speed and network performance, it means that no module can be added in the client side because the server wouldn't know about and wouldn't be able to resolve it.

Of course, a mechanism could be added to pass the addModule call to the server and act upon it on a per-session basis, but it is so complicated that we decided not do it.

What do you want to do exactly? Because you can deploy that modules in a shared bundle, for example. Do you really need to use `addModule` for your solution?

> And if so does that mean we can no longer do programmatic loading of modules?

You mean programmatic definition? I guess yes. Loading can still be done with Liferay.Loader.require(), but of course you cannot define modules dinamically, as you say.

**Comment by achicaiza** [comment]
Buenas días algún ejemplo que me podrían proporcionar para hacer algo parecido con lo que se hacía con el addModule, muchas gracias

**Comment by izaera** [comment]
Hi @achicaiza:

First of all, this is an international project which is read by people all over the world, so please use English, as it is its official language. If you are not fluent or don't fully understand it, just use http://translate.google.com to generate automatic translations and that will be enough for everyone to read your messages and for you to understand others'.

Regarding your question:

> Good morning some example that could provide me to do something similar to what was done with the addModule, thank you very much

There are no examples because there's no direct replacement for `Liferay.addModule`. Depending on what you used it for, there are several alternatives so we need to know what you exactly want to do to suggest a replacement.

**Comment by achicaiza** [comment]
Hi @izaera 

Good evening I have this example, where I have the external-libs project that has the angular library and then I have the other calendar-directive project where I use the angular one, it is a simple page with a date control that determines if the date chosen is or not in the weekend in both projects I occupy the Loader.addModule and I would like to know how it would be the way to use in version 7.2 of liferay, leave the link of the repository and attached the jar in case of not being able to generate them thank you for your help many Thank you.

https://github.com/achicaiza/liferay




[files.zip](https://github.com/liferay/liferay-amd-loader/files/3499850/files.zip)

**Comment by izaera** [comment]
@achicaiza Oh, I thought you were using the JS Toolkit. OK, the addModule does not work any more because you don't need it any more, as you can use standard ES6 or node syntax to require your modules. 

This is a whole new development paradigm that supersedes the old one with config generator and/or addModule, which was used in versions <7.0

So, I would recommend reading the [JS Toolkit wiki](https://github.com/liferay/liferay-js-toolkit/wiki) to get to know how the new setup works and especially [this](https://github.com/liferay/liferay-js-toolkit/wiki/How-to-use-generator-liferay-js) if you want to get started fast.

Hope that helps :-)

**Comment by izaera** [comment]
@achicaiza I forgot to mention the official docs too :point_right: https://portal.liferay.dev/docs/7-2/appdev/-/knowledge_base/a/developing-an-angular-application

They are probably more polished, if you want to start fast and don't get to know the internals.

**Comment by mlcanut** [comment]
Hi,
I have a custom js file and I would like load in Liferay 7.2 with AMD loader because I don´t want load js with <script> from my theme. In Liferay 7.1 with addModule was ok. In 7.2 I've deployed a module with a config.js file to define my custom code:
```
Liferay.Loader.define(
	'my-module',
	[],
	function() {
		return {
		       log: function(text) {
		           console.log('my-module: ' + text);
		       }
		   };
	});
```
My .bnd file is:
```
Bundle-Name: my-module
Bundle-SymbolicName: com.test.frontend.js
Bundle-Version: 1.0.0
Liferay-JS-Config: /META-INF/resources/config.js
Web-ContextPath: /my-module

Then in my portlet I require the module with:
Liferay.Loader.require(['my-module'], function (myModule) {
			console.log("LOADED!!!!!")	
		});

```
but console show me this error:
```
Error: Trying to define a module that was not registered: my-module

This usually means that someone is calling define() for a module that has not been previously required.
```

Could you tell me if my approach is correct?
Maybe my approach is not correct. 
I've checked
https://es.slideshare.net/clovisdasilvaneto/liferay-frontend-modules-and-dependencies-demystified-89680592

Thanks in advance
Regards
Miguel

**Comment by izaera** [comment]
@mlcanut This thread is all about the removal of the `addModule` function since 7.2, so no, your approach is not going to work.

The correct way now (since 7.2) is to create a JS Toolkit project and publish your modules from it. See [the wiki](https://github.com/liferay/liferay-js-toolkit/wiki/How-to-use-generator-liferay-js).

**Comment by mlcanut** [comment]
Thanksa lot @izaera !!
I'll try it!
