### ISSUE TITLE
Liferay AMD loader doesn't run on Windows 

### ISSUE THREAD

**Issue by ibhlool7** [liferay/liferay-amd-loader#216]
Hello 
I've cloned this project and tried to run it with node and I've just got these message :
```
liferay-amd-loader@4.0.0 build C:\Users\iman\Desktop\Spring\liferay-amd-loader
> node bin/build-loader.js
```
It must create a 'build' folder but it doesn't do anything 
my node version: 10.16.0
my OS: Windows [Version 10.0.16299.64]

**Comment by wincent** [comment]
I believe this got fixed as part of [the move](https://github.com/liferay/liferay-frontend-projects/pull/198) over to [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects), so I'm going to close this.

Among other things, we applied:

- [The fix for the `run()` failure](https://github.com/liferay/liferay-frontend-projects/pull/198/commits/57ecc9f107f57a98b936a95d343c72c7ee569eb5), and:
- We [stopped swallowing `run()` errors silently](https://github.com/liferay/liferay-frontend-projects/pull/198/commits/6184fd84f54eff607db1cf76e6b0ff95dd445f2b), and:
- We [removed the `jsdoc` calls](https://github.com/liferay/liferay-frontend-projects/pull/198/commits/9228a7cefa7ecde4b58a20b14a707e05cd8b832f) that have also been silently failing for years.
