### ISSUE TITLE
Non-npm based portlets and JS

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/liferay-amd-loader#224]
@achicaiza Oh, I thought you were using the JS Toolkit. OK, the addModule does not work any more because you don't need it any more, as you can use standard ES6 or node syntax to require your modules. 

This is a whole new development paradigm that supersedes the old one with config generator and/or addModule, which was used in versions <7.0

So, I would recommend reading the [JS Toolkit wiki](https://github.com/liferay/liferay-js-toolkit/wiki) to get to know how the new setup works and especially [this](https://github.com/liferay/liferay-js-toolkit/wiki/How-to-use-generator-liferay-js) if you want to get started fast.

Hope that helps :-)

_Originally posted by @izaera in https://github.com/liferay/liferay-amd-loader/issues/210#issuecomment-521130257_

**Comment by mfreeman-xtivia** [comment]
So is there no longer any way to do "old style" development of portlets that use JS?

ie i need to use C.js which depends on B.js  which maybe depends on jQuery. And this is a quick thing so i really dont want to go through the hassle of running the generator, using Vue/Angular/React, doing a build etc etc

In the past i could do this with liferayLoader.define() and liferayLoader.addModule() and its ilk to at least ensure that multiple copies of B did not end up on the page if multiple instances of the portlet were used on the same page etc

Am i just out-of-luck now if i want to do that more traditional style of JS usage?

**Comment by izaera** [comment]
Hi @mfreeman-xtivia . The problem here is that you cannot use `Liferay.Loader.addModule` because the module resolution is now being done server side.

If we allowed to do do `addModule` you could end up with potential dependency conflicts and that would break the server side resolution.

It is not impossible to design a protocol between the client and the server to avoid that problem, but it would add a lot of complexity to the solution for little benefit.

Just to make it easier to understand, imagine that you add `jQuery` via `addModule`, and then you deploy a portlet `X` that depends on `jQuery`. When the loader tries to instantiate `X`, it will ask the server about `X`'s dependencies and because the server doesn't know anything about `jQuery` you will end up with a missing module error.

**Comment by izaera** [comment]
However, I truly think it's quite easy to grab `jQuery`, put it inside an empty portlet created with the generator and then consume it from any other portlet. 

And it has the benefit that the model remains constant, while having two methods (the bundler vs addModule by hand) makes it more difficult to learn :thinking:
