### ISSUE TITLE
Magic Module for 'require' missing?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/liferay-amd-loader#92]
I noticed that this loader generates [AMD magic module](https://github.com/requirejs/requirejs/wiki/Differences-between-the-simplified-CommonJS-wrapper-and-standard-AMD-define#exports) definitions for the "module" and "export" dependencies such that a require statement like the one below succeeds....

~~~~
define("example", ["module", "exports", 'jquery'], function (module, exports,$) { ...
~~~~~

However the Liferay AMD loader doesn't appear to define a 'magic module' for 'require'. I tested this with a couple of examples, and including a module dependency on 'require' results in non-resolution of dependencies. This becomes problematic when using a number of transpilers that generate AMD-compliant code--a good example is TypeScript which generates module definitions that *always* include dependencies on 'require' and 'exports'...

module.ts file
~~~~
export var x=1;
~~~~

running *"tsc -m amd module. ts " produces the following module.js (which is the trouble)

~~~~
define(["require", "exports"], function (require, exports) {
    "use strict";
    exports.x = 1;
});
~~~~

**Comment by ipeychev** [comment]
Yeah, this is not supported. There was no transpiler which was producing a such an AMD module.
We will have to add this feature then.

**Comment by mfreeman-xtivia** [comment]
Thank you...

So in the short term as a workaround could I conceivably create my own module for require?

Perhaps something like this ???
~~~~
define ('require',[], function() {
  return require;
});
~~~~

**Comment by ipeychev** [comment]
You may try with this. Btw, do you have an example where TypeScript or some other transpiler generates a code where the passed `require` is used? In the example you posted it is unused.

**Comment by mfreeman-xtivia** [comment]
Let me dig one out and I will post here....

Also BTW it looks like in these cases the expectation is that **module** also exposes a read-only property 'id' in addition to 'exports'. Let me find some examples...

**Comment by ipeychev** [comment]
`id` and `uri`. It should be easy to add these too.

**Comment by mfreeman-xtivia** [comment]
So from what I can tell by looking at a variety of use cases I've seen is that the **require** magic-module is primarily used to do on-demand loading of modules. The **require** module exports a single function that can be used to do this...

The typical use case apparently is reacting to a user event like a click and then, and only then, triggering a require operation that loads a module (and presumably its dependencies as needed)....

So an example might be something like...

~~~~
define('sample', ['require'], function(require) {
    var somelib1 = require('somelib1');
    var somelib2 = require('somelib2');

    somelib1.someMethod(...)
}
~~~~

So implementing a mock version of 'require' would somehow need to trigger on-demand loading of the requested module---is this kind of thing even possible with the current version of the Liferay AMD loader?

**Comment by mfreeman-xtivia** [comment]
So thinking about it some and potentially answering my own question :-) syntactically this looks a little weird but i think it would do the job wouldn't it...

~~~~
define('require',[], function() {
   return function (requested_module) {
        require(requested_module, function(loaded_module) {
             return loaded_module;
        }
   };
})
~~~~

**Comment by ipeychev** [comment]
After reading again the "[specification](https://github.com/amdjs/amdjs-api/blob/master/AMD.md#simplified-commonjs-wrapping-)", here are my comments:
1. There is a local and global version of require. The local one we haven't implemented. There were two reasons:
 - There were no transpilers using it 
 - Our ambitious was not to implement a general purpose AMD loader, but to allow people to use `import` and `export` statements in Liferay Portal. However, during the time we added more and more things, like support for anonymous modules and on practice we cover most of the functionality of RequireJS plus things it was not able to do, like loading multiple modules via a combo loader.

Going back to this issue, here is how the `local` version of `require` is supposed to work and with `local` version I mean a `require` statement, written inside a `define` function.

1. The local require is either syncronous or asynchronous. Here is an example for _synchronous_ `require`:
```javascript
define(function(require, exports, module) {
  var c = require('c');
  exports.c = c;
});
```

As you see, require accepts only one argument - the module, which value should be returned. Please note there is no callback function.
What the loader should do in this case? Since the dependencies array in `define` is missing, it is supposed to 'scan' the body of the `define` function for synchronous require statements, to load the corresponding modules and then to call the callback in the define function. Then, the synchronous `require` function will detect that module 'c' is already loaded and to return its value.
What is important here is that `require` should __not__ try to load the module 'c' in the example above. If this module is not loaded, it should throw an exception.


2. Another valid example is when define specifies the dependencies explicitly and there is a local synchronous require, like this:
```javascript
define('sample', ['require', 'a', 'b'], function(require) {
  var a = require('a');
  var b = require('b');
});
```

In this case the local synchronous `require` should return the values of `a` and `b`. The Loader should load these in addition, before calling the factory function in `define`

The code like those below will throw an exception:
```javascript
// This will throw an exception
define('sample', ['require', 'a', 'b'], function(require) {
  var somelib1 = require('a');
  var somelib2 = require('b');
  var somelib2 = require('c'); // this module is not specified in the dependencies list
});
```
It will happen, because 'c' was not explicitly mentioned in the dependency array. This also means the [example](https://github.com/liferay/liferay-amd-loader/issues/92#issuecomment-263099201) you posted above will not work and it will throw an exception.

Now you see that unfortunately the workaround you suggest [here](https://github.com/liferay/liferay-amd-loader/issues/92#issuecomment-263099767) won't cover what I wrote above.

**Comment by mfreeman-xtivia** [comment]
@ipeychev thanks very much for the detailed explanation--its enlightening....

So here is my .02 though---feel free to disagree :-) --for better or for worse right now when dev tools talking about "generating AMD-compliant code" what they _really_ mean is generating "RequireJS-compliant code."  So if we're to attract and appeal to large swaths of JS developers it would seem that we need a loader that's at least "API-compliant" with RequireJS. (And the Liferay loader is pretty close to that already.)

Otherwise we create a scenario where a variety of popular JS development tools (and the potentially large number of  JS devs that use them) cannot really build JS code for the Liferay environment. I know of at least 2 cases where that is true now--namely **TypeScript** and **Riot.js**.

I am not a huge babel user, so I don't have any personal insight as to how it transpiles ES6 code to AMD-compliant modules but I will assume from current docs and experience that it must be generating code that works ok with the current loader's API?

**Comment by ipeychev** [comment]
This is correct. Babel was the first comprehensive transpiler, it was _de facto_ standard and that's why we focused on it. The Loader works fine with the code, generated by Babel.

Now, I think it won't hurt, if we implement the local synchronous version of `require` too. The question I have in my mind is does it worth the efforts.
TypeScript is used primary with Angular 2 and I think this is going to stay. This Loader won't be used in their infrastructure, they have their own and well working CLI. Others will use SystemJS.
About Riot, I can't say anything. You mentioned it, how is it related to the Loader?

**Comment by jbalsas** [comment]
Hey @ipeychev, @mfreeman-xtivia, keep in mind that we already have https://issues.liferay.com/browse/LPS-68298 in. This means that we can hide the loader and let other more specific systems handle this without the need for us to implement every edge case.

I agree that this would be a nice-to-have, but the fact that we keep adding more and more support seems to be contributing to change the original goal of this loader.

**Comment by mfreeman-xtivia** [comment]
I dunno guys --I can see both sides of the question here but just a couple more points related to the comments..
~~~
1.I know a number  of JS guys who love TypeScript and are not Angular guys. Unfortunately they cannot write Liferay-loader-compliant modules using TypeScript.
2. While its true that you can kick the loader into its own namespace when 68298 shows up, I am not sure in the end have multiple full blown module loaders (say Liferay's and Angular2's) all embedded and running around the same page is, in the end, a great idea. Yeah it'll probably work but its not a design I'd want to push somebody toward myself
3. In general, having learned a lot about the loader here lately due to @ipeychev  's great patience, and knowing that its going to be there, and be maintained, as part of Liferay, I'm inclined to try and use it as much as I possibly can.
~~~~

**Comment by jbalsas** [comment]
Hey @mfreeman-xtivia, I think we all agree with you that having more than one loader is less than desirable. That's why we tried to cover as much standard amd functionality as possible, so people could interop with it without the need of other loaders.

Trying to make ours the de-facto loader in liferay, however, would require us to implement other non-standard and module formats such as:
- [RequireJS plugin system](http://requirejs.org/docs/plugins.html)
- [Dojo Loader](http://dojotoolkit.org/reference-guide/1.10/loader/amd.html#loader-amd) and [Dojo-has feature detection for conditional loading](http://dojotoolkit.org/reference-guide/1.10/dojo/has.html#dojo-has)
- CommonJS support

I'm not saying we shouldn't try, just pointing out how much more there is to do if we want to stablish the loader as a general module loading solution and don't get in the way of existing developments.

We could also do the opposite. Remove everything that's not intrinsically needed for the liferay build system output so we end up with a very streamlined and optimized loader and let anyone else use their own whenever they need to get out of the ootb functionality.

**Comment by mfreeman-xtivia** [comment]
@jbalsas  I am not sure you would need to go that far.....fwiw... :-)

I think its fine to say "hey we are providing an AMD loader, period". So CJS folks sorry, go use Node. And if somebody *wants* to use Dojo and its own inherent loader, or Angular 2 and its SystemJS-based loader, fine, use LPS-68298 to kick the loader into its own namespace and have at it with your own loader.

But for those of us who *want* to be good AMD citizens, and would like to use devtools that are generating "AMD compliant" code (which is really RequireJS targeted) all we need is a couple of additional mods--the tweaks for properties like 'id' and 'uri' on the "module" module and an impl of " local require".

Anyway.... :-)

**Comment by jbalsas** [comment]
Makes sense, @mfreeman-xtivia, I'm just raising concerns that have been already voiced by others in the community. You also make a good point that now that we have `LPS-68298` we have an easier way to put the system in `loader-compatibility` mode, so I'm inclined to try to work on those additional tweaks. I'm just afraid these might be only the tip of the iceberg.

**Comment by ipeychev** [comment]
I vote for implementing the local require for two reasons:
1. It is part of the [specification](https://github.com/amdjs/amdjs-api/blob/master/AMD.md#simplified-commonjs-wrapping-).
2. Nothing prevents Babel to change tomorrow the way they transpile the code and start using the `require` as the TypeScript compiler does.

About the plugins of RequireJS, they are really optional and whoever wants to use them is happy to use RequireJS and namespace our Loader. Conditional loading we already have.

**Comment by jbalsas** [comment]
Let's go for it, then! 👍 

PS: I know we have conditional loading, it's just not compatible with the dojo's approach I mentioned, but I agree we've covered that with our loader-namespace feature.

**Comment by izaera** [comment]
Hi there. I'm going to implement the local require function but looking at https://github.com/requirejs/requirejs/wiki/Differences-between-the-simplified-CommonJS-wrapper-and-standard-AMD-define#sync-require I won't honor the "Simplified CommonJS Wrapper" scenario because it is way more difficult to implement than the AMD scenario, which doesn't need scanning inside the implementation function.

Nevertheless I have created a new issue to implement the "Simplified CommonJS Wrapper" scenario in the future if we see it fits (#112)
