### ISSUE TITLE
Create a Loader.addModule() flag to add senna.js data attributes

### ISSUE THREAD

**Issue by caneta** [liferay/liferay-amd-loader#94]
Being in a Liferay 7 environment and having so a [sennajs](http://sennajs.com/) library working under the hood, it would be nice to have a flag in the _Loader.addModule()_ API to manage [senna data attributes](http://sennajs.com/docs#dataattributes).

In this way the addition of `data-senna-track="permanent"` or the `data-senna-track="temporary"` to the <script> tag injected into the DOM would be cleaner and easier.

Is such a feature duable?

**Comment by jbalsas** [comment]
Hey @caneta, I don't think we should restrict this specifically to senna data attributes, but simply allow to add any specified attribute to the `script` element.

Another option would be to provide some kind of lifecycle so you could listen to `beforeScriptAppend` and receive the `script` element so you could do any kind of modifications you wished on it.

The first one, more declarative way might be cleaner, though.

**Comment by caneta** [comment]
Ok, I agree with a wider approach: adding any type of attribute could be useful.
I prefer the declarative option too.

**Comment by yuchi** [comment]
May I point to the fact that with combo loading we would introduce a very complex resource splitting algorithm? Otherwise either we loose the mentioned feature on combo loading or we get attributes applied to unwanted targets.

Also may I suggest to **not** use Senna’s attributes? If you need to execute actions at every page you probably need a different approach.

Instead of a `resources/do-something.js` that _imperatively_ executes some code and has side effects, you should go for a _factory_ approach.

Instead of:

```js
// resources/do-something.js:
document.body.classList.add('javascript-enabled');
// in you page:
require('resources/do-something');
```

do this:

```js
// resources/do-something.js:
export default function execute() {
  document.body.classList.add('javascript-enabled');
}
// in you page:
require('resources/do-something', function (doSomething) {
  doSomething.default();
});
```

**Comment by ipeychev** [comment]
@yuchi is correct, if such attributes are supported, then combo loading should be disabled.

Apart from that, I'm not convinced the Loader should support that. Its purpose is to load modules, not to deal with application logic.

**Comment by ipeychev** [comment]
Closing dure to inactivity.
